image: persik/asn1verification:1.1

pipelines:
  default:
    - step:
        script:
          - cd ..
          - git clone https://p3rsik@bitbucket.org/codeminders/asn1c.git
          - cd asn1verification/src
          - make clight coq
  branches:
    feature/*:
      - step:
          script:
            - cd ..
            - git clone https://p3rsik@bitbucket.org/codeminders/asn1c.git
            - cd asn1verification/src
            - make clight coq
    hotfix/*:
      - step:
          script:
            - cd ..
            - git clone https://p3rsik@bitbucket.org/codeminders/asn1c.git
            - cd asn1verification/src
            - make clight coq
