image: persik/asn1verification:1.1

pipelines:
  default:
    - step:
        script:
          - cd src
          - make clight coq
  branches:
    feature/*:
      - step:
          script:
            - cd src
            - make clight coq
    hotfix/*:
      - step:
          script:
            - cd src
            - make clight coq
