image: persik/asn1verification:1.0

pipelines:
  default:
    - step:
        script:
          - cp ../CompCert/compcert.ini .
          - cp ../CompCert/clightgen .
          - cd src
          - make clight coq
  branches:
    feature/*:
      - step:
          script:
            - cp ../CompCert/compcert.ini .
            - cp ../CompCert/clightgen .
            - cd src
            - make clight coq
    hotfix/*:
      - step:
          script:
            - cp ../CompCert/compcert.ini .
            - cp ../CompCert/clightgen .
            - cd src
            - make clight coq
