image: persik/asn1verification:1.1

pipelines:
  default:
    - step:
        script:
          - eval `ssh-agent`
          - cd ..
          - git clone git@bitbucket.org:codeminders/asn1c.git
          - cd /opt/atlassian/pipelines/agent/build/src
          - make clight coq
  branches:
    feature/*:
      - step:
          script:
            - eval `ssh-agent`
            - cd ..
            - git clone git@bitbucket.org:codeminders/asn1c.git
            - cd /opt/atlassian/pipelines/agent/build/src
            - make clight coq
    hotfix/*:
      - step:
          script:
            - eval `ssh-agent`
            - ls
            - pwd
            - cd ..
            - git clone git@bitbucket.org:codeminders/asn1c.git
            - cd /opt/atlassian/pipelines/agent/build/src
            - make clight coq
